quarkus.http.port=8080
%dev.quarkus.http.port=8082
hotel-eventbus-api-client/mp-rest/url=http://localhost:8080
%dev.hotel-eventbus-api-client/mp-rest/url=http://localhost:8081
#quarkus.log.category."org.eclipse.microprofile.rest.client".level=DEBUG
#quarkus.log.category."io.quarkus.restclient".level=DEBUG
#quarkus.log.category."org.apache.http.wire".level=DEBUG

# OpenAPI Configuration
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.info-title=Hotel Management Command API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.theme=material
quarkus.swagger-ui.doc-expansion=list
quarkus.swagger-ui.default-model-rendering=model
quarkus.swagger-ui.display-request-duration=true
quarkus.swagger-ui.deep-linking=true
quarkus.swagger-ui.show-extensions=true
quarkus.swagger-ui.show-common-extensions=true
quarkus.swagger-ui.try-it-out-enabled=true
quarkus.smallrye-openapi.store-schema-directory=target/generated/openapi