quarkus.http.port=8081
%dev.quarkus.http.port=8081
quarkus.eventstoredb.uri=esdb://localhost:2113?tls=false
hotel-query-api-client/mp-rest/url=http://localhost:8083
%dev.hotel-query-api-client/mp-rest/url=http://localhost:8083
#hotel-query-api-client/mp-rest/connectTimeout=5000
#hotel-query-api-client/mp-rest/readTimeout=5000

# Logging configuration
#quarkus.log.level=DEBUG
#quarkus.log.category."at.fhv.sys.eventbus".level=DEBUG
#quarkus.log.category."org.hibernate".level=INFO
#quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] (%t) %s%e%n

# OpenAPI Configuration
#quarkus.swagger-ui.always-include=true
#quarkus.swagger-ui.path=/swagger-ui
#quarkus.smallrye-openapi.info-title=Hotel Event Bus API
#quarkus.smallrye-openapi.info-version=1.0.0

# Fault Tolerance
#quarkus.smallrye-fault-tolerance.enabled=true

# Hibernate/JPA Konfiguration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
quarkus.hibernate-orm.packages=at.fhv.sys.eventbus.services

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=eventuser
quarkus.datasource.password=eventpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
# Run in Docker Terminal: docker run --name eventstore-postgres -e POSTGRES_USER=eventuser -e POSTGRES_PASSWORD=eventpass -e POSTGRES_DB=eventstore -p 5432:5432 -d postgres
