quarkus.http.port=8083
%dev.quarkus.http.port=8083

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=queryuser
quarkus.datasource.password=querypass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/sys
quarkus.hibernate-orm.database.generation=update
#docker run --name query-postgres -e POSTGRES_USER=queryuser -e POSTGRES_PASSWORD=querypass -e POSTGRES_DB=sys -p 5433:5432 -d postgres

# Hibernate Logging
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format_sql=true

# OpenAPI Configuration
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.info-title=Hotel Management Query API
quarkus.smallrye-openapi.info-version=1.0.0