quarkus.http.port=8083
%dev.quarkus.http.port=8083

# H2 Database configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:h2:mem:hotel;
quarkus.hibernate-orm.database.generation=update

# Hibernate Logging
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format_sql=true